import React, { useState } from 'react';
import SignIn from '../components/auth/SignIn';
import SignUp from '../components/auth/SignUp';
import { Brain } from 'lucide-react';
import { Navigate } from 'react-router-dom';
import { useAuthStore } from '../store/useAuthStore';

const AuthPage: React.FC = () => {
  const [isSignIn, setIsSignIn] = useState(true);
  const { isLoggedIn, isLoading } = useAuthStore();
  
  if (isLoggedIn) {
    return <Navigate to="/quiz" />;
  }
  
  return (
    <div className="min-h-[calc(100vh-4rem)] flex flex-col items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-purple-50 to-white">
      <div className="bg-white p-8 rounded-xl shadow-md w-full max-w-md border border-gray-100">
        <div className="flex flex-col items-center mb-8">
          <Brain className="h-12 w-12 text-purple-600" />
          <h1 className="mt-2 text-3xl font-bold text-gray-900">QuizGenius</h1>
          <p className="mt-2 text-center text-gray-600">
            Create custom quizzes on any topic with the power of AI
          </p>
        </div>
        
        {isSignIn ? (
          <SignIn onToggleForm={() => setIsSignIn(false)} />
        ) : (
          <SignUp onToggleForm={() => setIsSignIn(true)} />
        )}
      </div>
      
      <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3 w-full max-w-3xl">
        <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100">
          <h3 className="font-semibold text-gray-800 mb-2">Personalized Quizzes</h3>
          <p className="text-sm text-gray-600">Generate quizzes on any topic of your choice.</p>
        </div>
        
        <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100">
          <h3 className="font-semibold text-gray-800 mb-2">AI-Powered</h3>
          <p className="text-sm text-gray-600">Questions generated by Gemini AI for accuracy and relevance.</p>
        </div>
        
        <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100">
          <h3 className="font-semibold text-gray-800 mb-2">Detailed Explanations</h3>
          <p className="text-sm text-gray-600">Get explanations for every answer to enhance your learning.</p>
        </div>
      </div>
    </div>
  );
};

export default AuthPage;