import React from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuthStore } from '../store/useAuthStore';
import { Button } from '../components/ui/Button';
import { Brain, CheckCircle, LightbulbIcon, User, ArrowRight, Star, Sparkles, Trophy } from 'lucide-react';

const HomePage: React.FC = () => {
  const { isLoggedIn } = useAuthStore();
  const navigate = useNavigate();
  const location = useLocation();

  const handleStartLearning = () => {
    if (isLoggedIn) {
      navigate('/quiz');
    } else {
      navigate('/auth', { state: { from: location } });
    }
  };
  
  return (
    <div className="flex flex-col items-center">
      <div className="text-center max-w-4xl mx-auto relative">
        {/* Decorative elements */}
        <div className="absolute -top-20 -left-20 w-40 h-40 bg-purple-200 rounded-full blur-3xl opacity-20" />
        <div className="absolute -top-10 right-0 w-32 h-32 bg-indigo-200 rounded-full blur-3xl opacity-20" />
        
        <div className="flex justify-center mb-6 relative">
          <Brain className="h-20 w-20 text-purple-600 animate-pulse" />
          <div className="absolute inset-0 bg-purple-500/20 rounded-full blur-2xl" />
        </div>
        
        <h1 className="text-5xl sm:text-6xl font-bold text-gray-900 mb-6">
          Master Any Topic with <br />
          <span className="gradient-text">AI-Powered Quizzes</span>
        </h1>
        
        <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
          Transform your learning experience with personalized quizzes generated by Gemini AI. 
          Test your knowledge, get instant feedback, and learn at your own pace.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
          <Button 
            size="lg" 
            onClick={handleStartLearning}
            className="group"
          >
            Start Learning Now
            <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
          </Button>
        </div>
      </div>
      
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-8 mb-16">
        <div className="feature-card group">
          <div className="bg-purple-100 text-purple-700 p-3 rounded-full w-fit mb-4 group-hover:scale-110 transition-transform">
            <Sparkles className="h-6 w-6" />
          </div>
          <h3 className="text-xl font-semibold mb-3 group-hover:text-purple-600 transition-colors">Smart Questions</h3>
          <p className="text-gray-600">
            Our AI generates questions that adapt to your knowledge level, from basic concepts to advanced applications.
          </p>
        </div>
        
        <div className="feature-card group">
          <div className="bg-blue-100 text-blue-700 p-3 rounded-full w-fit mb-4 group-hover:scale-110 transition-transform">
            <Star className="h-6 w-6" />
          </div>
          <h3 className="text-xl font-semibold mb-3 group-hover:text-blue-600 transition-colors">Custom Experience</h3>
          <p className="text-gray-600">
            Choose your topic, difficulty, and preferred language. Get a tailored learning experience just for you.
          </p>
        </div>
        
        <div className="feature-card group">
          <div className="bg-green-100 text-green-700 p-3 rounded-full w-fit mb-4 group-hover:scale-110 transition-transform">
            <Trophy className="h-6 w-6" />
          </div>
          <h3 className="text-xl font-semibold mb-3 group-hover:text-green-600 transition-colors">Track Progress</h3>
          <p className="text-gray-600">
            Monitor your improvement with detailed feedback and explanations for every answer.
          </p>
        </div>
      </div>
      
      <div className="w-full max-w-6xl mx-auto mb-16">
        <div className="gradient-bg rounded-2xl shadow-xl p-8 sm:p-12 text-white relative overflow-hidden group">
          <div className="relative z-10">
            <h2 className="text-3xl font-bold mb-4">Ready to elevate your learning?</h2>
            <p className="text-purple-100 mb-6 max-w-xl">
              Join thousands of learners who are already using QuizGenius to master new subjects.
            </p>
            <Button
              onClick={handleStartLearning}
              className="bg-white text-purple-700 hover:bg-purple-50 group"
            >
              Sign Up Free
              <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
            </Button>
          </div>
          
          {/* Animated background elements */}
          <div className="absolute inset-0 bg-gradient-to-r from-purple-600/20 to-indigo-600/20 backdrop-blur-3xl group-hover:scale-105 transition-transform duration-500" />
          <div className="absolute -right-20 -bottom-20 w-64 h-64 bg-white/10 rounded-full blur-2xl group-hover:scale-110 transition-transform duration-500" />
          <div className="absolute -left-10 -top-10 w-40 h-40 bg-purple-400/20 rounded-full blur-2xl group-hover:scale-110 transition-transform duration-500" />
        </div>
      </div>
    </div>
  );
};

export default HomePage;